### ISSUE TITLE
Installazione per San Gregorio di Catania

### ISSUE THREAD

**Issue by sibylmichelangelotodaro** [Gualty/Diffy#1]
Ciao,

complimenti per il BOTDifferenziata è veramente ben fatto. Da Aci Catena mi sono trasferito a SanGregorio di Catania e mi piacerebbe averlo anche qui.
Per fare una nuova installazione ci pensi tu? Potrei darti anche una mano. Oppure se vuoi ci posso pensare anche io.

Fammi sapere 
Grazie
Buona giornata

**Comment by Gualty** [comment]
Ciao,
scusa la risposta in ritardo ma leggo solo ora.
Hai la possibilità di mandarmi il link del sito del comune con tutti i dettagli?

Posso provare io a crearlo nel tempo libero, quindi non assicuro tempi brevi :)

**Comment by sibylmichelangelotodaro** [comment]
Ciao,

a questo link trovi i dettagli http://www.comune.san-gregorio-di-catania.ct.it/Repository/Sangregorio/Upload/2018/id_4041/IMG-20180203-WA0019.jpg

Come posso aiutarti?
Mi piacerebbe capire come hai fatto.

Grazie

**Comment by Gualty** [comment]
Grazie per il link.
Nella pagina principale del progetto è spiegato tutto. Inserisco tutti i dettagli della raccolta differenziata nelle varie sezioni del codice.

Appena ho notizie ti faccio sapere e potrai essere tra i primi a poterlo testare!

**Comment by Gualty** [comment]
OTTIME NOTIZIE!

Ho trovato oggi stesso un po' di tempo e.... ecco il bot per [San Gregorio di Catania](https://telegram.me/DiffSanGregoriobot)

Fammi sapere cosa ne pensi e se ci sono errori da correggere! 

Ciao!

**Comment by sibylmichelangelotodaro** [comment]
Bene! 

Ti tengo aggiornato 

Grazie 




Da: "Gualtiero" <notifications@github.com> 
A: "Gualty/BOTDifferenziata" <BOTDifferenziata@noreply.github.com> 
Cc: "sibylmichelangelotodaro" <michelangelo.todaro@sibyl.it>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 9 ottobre 2018 21:03:40 
Oggetto: Re: [Gualty/BOTDifferenziata] Installazione per San Gregorio di Catania (#1) 



OTTIME NOTIZIE! 

Ho trovato oggi stesso un po' di tempo e.... ecco il bot per San Gregorio di Catania 


Fammi sapere cosa ne pensi e se ci sono errori da correggere! 

Ciao!

**Comment by sibylmichelangelotodaro** [comment]
Ciao, 

non funzionano le notifiche e se clicco sul pulsante mi chiede sempre se voglio attivarle. 

Ciao 





Da: "Michelangelo Todaro" <michelangelo.todaro@sibyl.it> 
A: "Gualty/BOTDifferenziata" <reply@reply.github.com> 
Cc: "Gualty/BOTDifferenziata" <BOTDifferenziata@noreply.github.com>, "Author" <author@noreply.github.com> 
Inviato: Mercoledì, 10 ottobre 2018 9:47:55 
Oggetto: Re: [Gualty/BOTDifferenziata] Installazione per San Gregorio di Catania (#1) 

Bene! 

Ti tengo aggiornato 

Grazie 




Da: "Gualtiero" <notifications@github.com> 
A: "Gualty/BOTDifferenziata" <BOTDifferenziata@noreply.github.com> 
Cc: "sibylmichelangelotodaro" <michelangelo.todaro@sibyl.it>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 9 ottobre 2018 21:03:40 
Oggetto: Re: [Gualty/BOTDifferenziata] Installazione per San Gregorio di Catania (#1) 



OTTIME NOTIZIE! 

Ho trovato oggi stesso un po' di tempo e.... ecco il bot per San Gregorio di Catania 


Fammi sapere cosa ne pensi e se ci sono errori da correggere! 

Ciao!

**Comment by Gualty** [comment]
Ciao, si le notifiche non sono ancora attive, infatti quando provi ad attivarle c’è scritto che non è attiva questa funzione. Sto cercando un server migliore per automatizzare le notifiche 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gualty** [comment]
Ciao, notifiche attive. Dovresti già averne ricevuta una per prova ma da domani arriveranno automaticamente alle ore 20:00.

**Comment by sibylmichelangelotodaro** [comment]
Confermo, ricevuta.Il 11 ott 2018 9:36 PM, Gualtiero <notifications@github.com> ha scritto:Ciao, notifiche attive. Dovresti già averne ricevuta una per prova ma da domani arriveranno automaticamente alle ore 20:00.

**Comment by sibylmichelangelotodaro** [comment]
Ciao, 

una precisazione sul Vetro: 



    * si raccoglie separatamente dalla plastica 
    * si espone solo il martedì insieme all'umido in un sacchetto separato 

Potremmo aggiungere inoltre che i giorni in cui si espone l'umido, in un sacchetto separato si possono esporre i pannolini. 

Ciao Grazie 







Da: "Gualtiero" <notifications@github.com> 
A: "Gualty/Diffy" <Diffy@noreply.github.com> 
Cc: "sibylmichelangelotodaro" <michelangelo.todaro@sibyl.it>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 16 ottobre 2018 23:25:54 
Oggetto: Re: [Gualty/Diffy] Installazione per San Gregorio di Catania (#1) 



Closed #1 .

**Comment by Gualty** [comment]
Ciao, scusa per il ritardo.

Ho provveduto a correggere le pagine dedicate al vetro ed aggiornare il calendario.
Ho corretto anche i sacchetti perché nell’ultima versione non ci sono più i sacchetti colorati ma solo trasparenti o qualunque per l’indifferenziato.

Grazie e mi raccomando, diffondi!
